Repository NoWasteInMyFridge/NoWasteInMyFridge, pull requests merged in 2024-01, with the labels that each got.

#4 Login System - part UI
  .gitignore
  .idea/inspectionProfiles/Project_Default.xml
  .idea/kotlinc.xml
  .idea/migrations.xml
  app/build.gradle.kts
  app/src/main/java/com/develop/nowasteinmyfridge/BottomNavGraph.kt
  app/src/main/java/com/develop/nowasteinmyfridge/MainActivity.kt
  app/src/main/java/com/develop/nowasteinmyfridge/Navigation.kt
  app/src/main/java/com/develop/nowasteinmyfridge/Screen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/screens/Adding.kt
  app/src/main/java/com/develop/nowasteinmyfridge/screens/HomeScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/screens/Inventory.kt
  app/src/main/java/com/develop/nowasteinmyfridge/screens/MainScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/screens/Setting.kt
  app/src/main/java/com/develop/nowasteinmyfridge/screens/login/LoginScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/ui/theme/BottomBarScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/ui/theme/Color.kt
  app/src/main/res/mipmap-hdpi/footer_login.webp
  app/src/main/res/mipmap-hdpi/header_login.webp
  app/src/main/res/mipmap-mdpi/footer_login.webp
  app/src/main/res/mipmap-mdpi/header_login.webp
  app/src/main/res/mipmap-xhdpi/footer_login.webp
  app/src/main/res/mipmap-xhdpi/header_login.webp
  app/src/main/res/mipmap-xxhdpi/footer_login.webp
  app/src/main/res/mipmap-xxhdpi/header_login.webp
  app/src/main/res/mipmap-xxxhdpi/footer_login.webp
  app/src/main/res/mipmap-xxxhdpi/header_login.webp
  app/src/main/res/values/strings.xml
Labels: Ready for review

#11 Adding Screen - part UI
  app/src/main/java/com/develop/nowasteinmyfridge/screens/Adding.kt
  app/src/main/java/com/develop/nowasteinmyfridge/screens/Setting.kt
  app/src/main/java/com/develop/nowasteinmyfridge/ui/theme/Color.kt
  app/src/main/res/mipmap-hdpi/add_photo.webp
  app/src/main/res/mipmap-mdpi/add_photo.webp
  app/src/main/res/mipmap-xhdpi/add_photo.webp
  app/src/main/res/mipmap-xxhdpi/add_photo.webp
  app/src/main/res/mipmap-xxxhdpi/add_photo.webp
  app/src/main/res/values/strings.xml
Labels: Feature

#7 Login System - part Firebase
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/develop/nowasteinmyfridge/BottomNavGraph.kt
  app/src/main/java/com/develop/nowasteinmyfridge/MainActivity.kt
  app/src/main/java/com/develop/nowasteinmyfridge/MainScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/Navigation.kt
  app/src/main/java/com/develop/nowasteinmyfridge/NoWasteInMyFridgeApp.kt
  app/src/main/java/com/develop/nowasteinmyfridge/data/repository/AuthRepository.kt
  app/src/main/java/com/develop/nowasteinmyfridge/data/repository/AuthRepositoryImpl.kt
  app/src/main/java/com/develop/nowasteinmyfridge/di/AppModule.kt
  app/src/main/java/com/develop/nowasteinmyfridge/domain/LoginUserUseCase.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/adding/AddingScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/home/HomeScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/inventory/InventoryScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/login/LoginScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/login/LoginViewModel.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/login/SignInState.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/setting/SettingScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/screens/Inventory.kt
  app/src/main/java/com/develop/nowasteinmyfridge/util/Resource.kt
  build.gradle.kts
Labels: enhancement

#18 SignUp System and Display Profile
  app/build.gradle.kts
  app/src/main/java/com/develop/nowasteinmyfridge/AppNavHost.kt
  app/src/main/java/com/develop/nowasteinmyfridge/AuthNavGraph.kt
  app/src/main/java/com/develop/nowasteinmyfridge/BottomBarScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/BottomNavGraph.kt
  app/src/main/java/com/develop/nowasteinmyfridge/MainActivity.kt
  app/src/main/java/com/develop/nowasteinmyfridge/MainScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/Screen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/data/model/MenuItem.kt
  app/src/main/java/com/develop/nowasteinmyfridge/data/model/UserCreate.kt
  app/src/main/java/com/develop/nowasteinmyfridge/data/model/UserProfile.kt
  app/src/main/java/com/develop/nowasteinmyfridge/data/repository/FirebaseFirestoreRepository.kt
  app/src/main/java/com/develop/nowasteinmyfridge/data/repository/FirebaseFirestoreRepositoryImpl.kt
  app/src/main/java/com/develop/nowasteinmyfridge/domain/CreateUserUseCase.kt
  app/src/main/java/com/develop/nowasteinmyfridge/domain/GetUserInfoUseCase.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/account/AccountScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/account/AccountViewModel.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/adding/AddingScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/login/LoginScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/setting/MenuSettingScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/setting/SettingScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/setting/SettingViewModel.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/setting/navigation/SettingNavGraph.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/signup/SignUpScreen.kt
  app/src/main/java/com/develop/nowasteinmyfridge/feature/signup/SignupViewModel.kt
  app/src/main/java/com/develop/nowasteinmyfridge/util/Result.kt
  app/src/main/res/values/strings.xml
Labels: Feature
